# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_registerhomepagetest(self):
    self.driver.get("http://127.0.0.1:5000//")
    self.driver.set_window_size(1440, 806)
    self.driver.find_element(By.LINK_TEXT, "Register here!").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("asdf@emial.com")
    self.driver.find_element(By.ID, "name").send_keys("Guest User")
    self.driver.find_element(By.ID, "dateofbirth").send_keys("0002-01-01")
    self.driver.find_element(By.ID, "dateofbirth").send_keys("0020-01-01")
    self.driver.find_element(By.ID, "dateofbirth").send_keys("0200-01-01")
    self.driver.find_element(By.ID, "dateofbirth").send_keys("2000-01-01")
    self.driver.find_element(By.ID, "major").send_keys("data science")
    self.driver.find_element(By.ID, "year").send_keys("3")
    self.driver.find_element(By.ID, "studentid").send_keys("11111111")
    self.driver.find_element(By.ID, "username").send_keys("guestuser123")
    self.driver.find_element(By.ID, "password").send_keys("pwd")
    self.driver.find_element(By.ID, "password2").send_keys("pwd")
    self.driver.find_element(By.ID, "submit").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".bg-text > h1:nth-child(1)").text == "Welcome Guest User!"
  
  def test_checkAccountdetails(self):
    self.driver.get("http://127.0.0.1:5000/home-page")
    self.driver.set_window_size(1440, 806)
    self.driver.find_element(By.CSS_SELECTOR, ".nav-item:nth-child(5) > .nav-link").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) > td").text == "guestuser123"
    assert self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) > td").text == "asdf@emial.com"
    assert self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) > td").text == "2000-01-01"
    assert self.driver.find_element(By.CSS_SELECTOR, ".card-body > .mb-0:nth-child(1)").text == "Student ID:11111111"
    assert self.driver.find_element(By.CSS_SELECTOR, ".mb-0:nth-child(2)").text == "Major:data science"
    assert self.driver.find_element(By.CSS_SELECTOR, ".mb-0:nth-child(3)").text == "Year:3"
  
  def test_checkeditprofile(self):
    self.driver.get("http://127.0.0.1:5000/home-page")
    self.driver.set_window_size(1440, 806)
    self.driver.find_element(By.CSS_SELECTOR, ".nav-item:nth-child(5) > .nav-link").click()
    self.driver.find_element(By.LINK_TEXT, "Edit Account Details").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) > td").click()
    element = self.driver.find_element(By.ID, "username")
    assert element.is_enabled() is True
    element = self.driver.find_element(By.ID, "email")
    assert element.is_enabled() is True
    element = self.driver.find_element(By.ID, "dateofbirth")
    assert element.is_enabled() is True
    element = self.driver.find_element(By.ID, "studentid")
    assert element.is_enabled() is True
    element = self.driver.find_element(By.ID, "major")
    assert element.is_enabled() is True
    element = self.driver.find_element(By.ID, "year")
    assert element.is_enabled() is True
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("Username1")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("username1@gmail.com")
    self.driver.find_element(By.ID, "dateofbirth").click()
    self.driver.find_element(By.ID, "dateofbirth").click()
    self.driver.find_element(By.ID, "dateofbirth").click()
    self.driver.find_element(By.ID, "dateofbirth").send_keys("2000-01-08")
    self.driver.find_element(By.ID, "studentid").click()
    self.driver.find_element(By.CSS_SELECTOR, ".card-body > .mb-0:nth-child(1)").click()
    self.driver.find_element(By.ID, "studentid").send_keys("22222222")
    self.driver.find_element(By.ID, "major").click()
    self.driver.find_element(By.ID, "major").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mb-0:nth-child(2)").click()
    self.driver.find_element(By.ID, "major").send_keys("Finance")
    self.driver.find_element(By.ID, "year").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mb-0:nth-child(3)").click()
    self.driver.find_element(By.ID, "year").send_keys("5")
    self.driver.find_element(By.CSS_SELECTOR, ".pt-0").click()
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".nav-item:nth-child(5) > .nav-link").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) > td").text == "Username1"
    assert self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) > td").text == "username1@gmail.com"
    assert self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) > td").text == "2000-01-08"
    assert self.driver.find_element(By.CSS_SELECTOR, ".card-body > .mb-0:nth-child(1)").text == "Student ID:22222222"
    assert self.driver.find_element(By.CSS_SELECTOR, ".mb-0:nth-child(2)").text == "Major:Finance"
    assert self.driver.find_element(By.CSS_SELECTOR, ".mb-0:nth-child(3)").text == "Year:5"
  
  def test_checkcontents(self):
    self.driver.get("http://127.0.0.1:5000/home-page")
    self.driver.set_window_size(1440, 806)
    self.driver.find_element(By.ID, "navbarDropdown").click()
    self.driver.find_element(By.CSS_SELECTOR, ".show > .dropdown-item:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".carousel-control-next-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".carousel-control-next-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".carousel-control-next-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".carousel-control-next-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".carousel-control-next-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".carousel-control-next-icon").click()
    elements = self.driver.find_elements(By.LINK_TEXT, "Click here to continue learning about Enrolment!")
    assert len(elements) > 0
    assert self.driver.find_element(By.LINK_TEXT, "Click here to continue learning about Enrolment!").text == "Click here to continue learning about Enrolment!"
  
  def test_checkquizzes(self):
    self.driver.get("http://127.0.0.1:5000/home-page")
    self.driver.set_window_size(1440, 806)
    self.driver.find_element(By.CSS_SELECTOR, ".nav-item:nth-child(4) > #navbarDropdown").click()
    self.driver.find_element(By.CSS_SELECTOR, ".show > .dropdown-item:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "Undergraduate Test").click()
    self.driver.find_element(By.NAME, "question0").click()
    self.driver.find_element(By.CSS_SELECTOR, ".slideQuiz:nth-child(5)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".slideQuiz:nth-child(4)").click()
    self.driver.find_element(By.ID, "next").click()
    self.driver.find_element(By.NAME, "question1").click()
    self.driver.find_element(By.ID, "next").click()
    self.driver.find_element(By.CSS_SELECTOR, ".active-slide label:nth-child(2) > input").click()
    self.driver.find_element(By.ID, "next").click()
    self.driver.find_element(By.CSS_SELECTOR, ".active-slide label:nth-child(2) > input").click()
    self.driver.find_element(By.ID, "next").click()
    self.driver.find_element(By.NAME, "question4").click()
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".active-slide").click()
    self.driver.find_element(By.CSS_SELECTOR, ".slideQuiz:nth-child(4)").click()
    assert self.driver.find_element(By.ID, "results").text == "4 out of 5 correct"
  
