"""empty message

Revision ID: 31b12a9fa6eb
Revises: c50a5054da30
Create Date: 2021-05-16 01:47:39.528890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31b12a9fa6eb'
down_revision = 'c50a5054da30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('major', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('studentid', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_major'), 'user', ['major'], unique=False)
    op.create_index(op.f('ix_user_studentid'), 'user', ['studentid'], unique=True)
    op.create_index(op.f('ix_user_year'), 'user', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_year'), table_name='user')
    op.drop_index(op.f('ix_user_studentid'), table_name='user')
    op.drop_index(op.f('ix_user_major'), table_name='user')
    op.drop_column('user', 'studentid')
    op.drop_column('user', 'year')
    op.drop_column('user', 'major')
    # ### end Alembic commands ###
