"""added scores table

Revision ID: 82579b73d2e0
Revises: 83a82259c2f5
Create Date: 2021-05-17 15:46:42.905866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82579b73d2e0'
down_revision = '83a82259c2f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_user_major', table_name='user')
    op.drop_index('ix_user_studentid', table_name='user')
    op.drop_index('ix_user_year', table_name='user')
    op.drop_column('user', 'year')
    op.drop_column('user', 'studentid')
    op.drop_column('user', 'major')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('major', sa.VARCHAR(length=64), nullable=True))
    op.add_column('user', sa.Column('studentid', sa.INTEGER(), nullable=True))
    op.add_column('user', sa.Column('year', sa.INTEGER(), nullable=True))
    op.create_index('ix_user_year', 'user', ['year'], unique=False)
    op.create_index('ix_user_studentid', 'user', ['studentid'], unique=False)
    op.create_index('ix_user_major', 'user', ['major'], unique=False)
    op.drop_table('score')
    # ### end Alembic commands ###
