"""scores table

Revision ID: eaf37273a18f
Revises: 82579b73d2e0
Create Date: 2021-05-17 16:11:20.223091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaf37273a18f'
down_revision = '82579b73d2e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('quiz_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score', 'quiz_id')
    # ### end Alembic commands ###
